# Generated by Django 5.2.14 on 2026-09-28 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_chatsession_autonomy_toolpermission_match'),
        ('core', '0013_organization_userprofile_active_org_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.organization'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='share_solutions',
            field=models.BooleanField(default=False),
        ),
    ]
