# Generated by Django 5.2.14 on 2026-09-28 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0013_organization_userprofile_active_org_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared', models.BooleanField(default=False)),
                ('author_name', models.CharField(blank=True, default='', max_length=150)),
                ('problem', models.CharField(max_length=500)),
                ('symptoms', models.TextField(blank=True, default='')),
                ('root_cause', models.TextField(blank=True, default='')),
                ('resolution', models.TextField()),
                ('environment', models.JSONField(blank=True, default=dict)),
                ('claims', models.JSONField(blank=True, default=list)),
                ('volatility', models.CharField(default='procedure', max_length=20)),
                ('phrasings', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('needs_check', 'Needs check'), ('superseded', 'Superseded'), ('retracted', 'Retracted')], default='active', max_length=12)),
                ('valid_as_of', models.DateTimeField()),
                ('doubtful', models.BooleanField(default=False)),
                ('doubt_reason', models.CharField(blank=True, default='', max_length=500)),
                ('confirmations', models.IntegerField(default=0)),
                ('failures', models.IntegerField(default=0)),
                ('reuse_count', models.IntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('captured_by', models.CharField(choices=[('auto', 'Captured automatically'), ('tool', 'Saved by the assistant'), ('user', 'Saved by a person')], default='tool', max_length=8)),
                ('source_session', models.CharField(blank=True, default='', max_length=64)),
                ('source_message_id', models.BigIntegerField(blank=True, null=True)),
                ('embed_version', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solutions', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='core.organization')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='solutions.solution')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SolutionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('confirmed', 'Worked'), ('failed', 'Did not work'), ('doubt', 'Looks doubtful'), ('cleared', 'Doubt cleared'), ('verified', 'Re-checked and still true'), ('contradicted', 'Re-checked and no longer true')], max_length=14)),
                ('model', models.CharField(blank=True, default='', max_length=150)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='solutions.solution')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SolutionSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(db_index=True, max_length=64)),
                ('text', models.CharField(max_length=300)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='solutions.solution')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_index=True, max_length=64)),
                ('weight', models.FloatField()),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='solutions.solution')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='question', max_length=10)),
                ('vector', models.BinaryField()),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vectors', to='solutions.solution')),
            ],
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['org', 'shared', 'status'], name='solutions_s_org_id_556e6d_idx'),
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['author', 'org', 'status'], name='solutions_s_author__54fc06_idx'),
        ),
        migrations.AddIndex(
            model_name='solutionreview',
            index=models.Index(fields=['solution', '-created_at'], name='solutions_s_solutio_d9718f_idx'),
        ),
    ]
